# Generated by Django 3.1.13 on 2021-12-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientslist',
            options={'verbose_name': 'Список ингредиентов', 'verbose_name_plural': 'Список ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='tagslist',
            options={'verbose_name': 'Список тегов', 'verbose_name_plural': 'Список тегов'},
        ),
        migrations.AddConstraint(
            model_name='ingredientslist',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique ingredient'),
        ),
        migrations.AddConstraint(
            model_name='tagslist',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique tag'),
        ),
    ]
