# Generated by Django 3.1.13 on 2021-11-15 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientsList', to='ingredients.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes_tags', to='tags.Tag', verbose_name='Теги рецепта'),
        ),
        migrations.AddField(
            model_name='markeduserrecipes',
            name='fovorited_recipe',
            field=models.ManyToManyField(blank=True, related_name='marked_favorited_recipes', to='recipes.Recipe', verbose_name='Понравившиеся рецепты'),
        ),
        migrations.AddField(
            model_name='markeduserrecipes',
            name='recipe_for_download',
            field=models.ManyToManyField(blank=True, related_name='marked_download_recipes', to='recipes.Recipe', verbose_name='Рецепты для скачивания'),
        ),
        migrations.AddField(
            model_name='markeduserrecipes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marked_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ingredientslist',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_ingredients', to='ingredients.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientslist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_recipe', to='recipes.recipe'),
        ),
    ]
