# Generated by Django 3.1.13 on 2021-11-16 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211115_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Автор рецепта')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='Картинка рецепта')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.PositiveSmallIntegerField(verbose_name='Время приготовления')),
                ('tags', models.PositiveBigIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Теги рецепта')),
                ('ingredients', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ингредиенты')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рецепт_new',
                'verbose_name_plural': 'Рецепты_new',
                'ordering': ('-publication_date',),
            },
        ),
    ]
