# Generated by Django 3.1.13 on 2021-11-16 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipenew',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipenew',
            name='tags',
        ),
        migrations.CreateModel(
            name='TagsListNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Теги')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipes.recipenew', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsListNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ингредиенты')),
                ('amount', models.PositiveSmallIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipenew', verbose_name='Рецепт')),
            ],
        ),
    ]
