# Generated by Django 3.1.13 on 2021-11-16 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211116_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagslistnew',
            name='tag',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тег'),
        ),
    ]
