version: '3.3'

services:
  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_django/
      - media_value:/var/html/media/
      - ../docs:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
    networks: 
      - foodgram_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/envfiles/.env.dev_b+f
    networks: 
      - foodgram_network

  web:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev_b+f
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8080:8000
    volumes:
      - ../backend:/usr/src/app/web
      - ../data:/usr/src/app/data
      - static_value:/usr/src/app/web/static_django/
      - media_value:/usr/src/app/web/media/
    env_file:
      - ../backend/envfiles/.env.dev_b+f
    depends_on:
      - db
    networks: 
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge

volumes:
  postgres_data:
  static_value:
  media_value: