# Generated by Django 3.1.13 on 2021-12-14 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Подписчик')),
                ('author', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('follower', 'author'), name='unique subscription'),
        ),
    ]
